call run_b3d_reader_for_env.bat aa %*
call run_b3d_reader_for_env.bat ab %*
call run_b3d_reader_for_env.bat ac %*
call run_b3d_reader_for_env.bat ad %*
call run_b3d_reader_for_env.bat ae %*
call run_b3d_reader_for_env.bat af %*
call run_b3d_reader_for_env.bat ag %*
call run_b3d_reader_for_env.bat ah %*
call run_b3d_reader_for_env.bat aj %*
call run_b3d_reader_for_env.bat ak %*
call run_b3d_reader_for_env.bat al %*
call run_b3d_reader_for_env.bat am %*
call run_b3d_reader_for_env.bat ap %*
call run_b3d_reader_for_env.bat aq %*
call run_b3d_reader_for_env.bat ar %*
call run_b3d_reader_for_env.bat as %*
call run_b3d_reader_for_env.bat at %*
call run_b3d_reader_for_env.bat au %*
call run_b3d_reader_for_env.bat av %*
call run_b3d_reader_for_env.bat aw %*
call run_b3d_reader_for_env.bat ax %*
call run_b3d_reader_for_env.bat ba %*
call run_b3d_reader_for_env.bat bb %*
call run_b3d_reader_for_env.bat bc %*
call run_b3d_reader_for_env.bat bd %*
call run_b3d_reader_for_env.bat be %*
call run_b3d_reader_for_env.bat bf %*
call run_b3d_reader_for_env.bat bg %*
call run_b3d_reader_for_env.bat ca %*
call run_b3d_reader_for_env.bat cb %*
call run_b3d_reader_for_env.bat cc %*
call run_b3d_reader_for_env.bat ce %*
call run_b3d_reader_for_env.bat cf %*
call run_b3d_reader_for_env.bat ch %*
call run_b3d_reader_for_env.bat da %*
call run_b3d_reader_for_env.bat db %*
call run_b3d_reader_for_env.bat dc %*
call run_b3d_reader_for_env.bat dq %*
call run_b3d_reader_for_env.bat dr %*
